### ISSUE TITLE
Why not to use a subclass of block_edit_form instead of config_instance.html

### ISSUE THREAD

**Issue by mudrd8mz** [juacas/moodle-block_quest_classification#4]
IIRC, the config_instance.html has been deprecated since years ago.

**Comment by mudrd8mz** [comment]
https://docs.moodle.org/dev/Blocks#Configure_That_Out

**Comment by juacas** [comment]
Sorry, that file was forgotten there by mistake. It is not used. block_edit_form is actually used for configuration.
